name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - name: Build script
            run: ./build_step.sh
          - name: Trigger deployment
            run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}